### ISSUE TITLE
[Question] Unique device identifier using fingerprint library

### ISSUE THREAD

**Issue by rajkannan-carousell** [fingerprintjs/fingerprintjs-android#102]
Hello Team, 

   While going through the documentation available in github/website, i found that, we cannot generate unique identifier using device id, fingerprint after factory reset of device.

Our main requirement is to keep the same device id or some identifier even after factory reset. 

Let's say  if user is using device 1, even after multiple reinstalls of app, and factory reset, we should use the same identifier for Fraud detection

With the available documentation, i cannot conclude on what should i use clearly.

Fingerprint -> Stable, Optimal, Unique 

* Stable -> seems like a hardware id which will be same across same model of devices
* Unique -> generates unique id. But it tells it can change if some application setting or device config changes . But not sure for what changes it will change ??
* Optimal -> somewhere in between. 

Device id -> generates a unique id using many signals and will change after factory reset which is breaking our requirement.

Any suggestion on how to use fingerprint js library to achieve our goals. Our primary goal is to find the same device coming back again to our platform. Thanks.

**Comment by Alexey-Verkhovsky** [comment]
Hello @rajkannan-carousell! 

Correct identification between factory reset is very challenging when no permissions is provided on a device for using hardware identifiers (like IMEI or MAC address). If you have constraints on using the fingerprintjs-android only – I would experiment with the [[Custom Fingerprint API](https://github.com/fingerprintjs/fingerprintjs-android/blob/main/docs/api_reference.md#raw-signals-access-and-custom-fingerprinting)](https://github.com/fingerprintjs/fingerprintjs-android/blob/main/docs/api_reference.md#raw-signals-access-and-custom-fingerprinting). You may enrich the hardware fingerprint with some device settings to get more unique identifier. E.g. your signals set will be somewhere in between Stable and Unique [[fingerprints](https://github.com/fingerprintjs/fingerprintjs-android/blob/main/docs/api_reference.md#increasing-the-uniqueness-of-fingerprints)](https://github.com/fingerprintjs/fingerprintjs-android/blob/main/docs/api_reference.md#increasing-the-uniqueness-of-fingerprints).

As a more simple and correct solution, you may check out our new Smart Signal: Factory reset detection. In the return [[value](https://dev.fingerprint.com/reference/getevent)](https://dev.fingerprint.com/reference/getevent) there is a seconds-accurate timestamp which will help you distincting factory-reset devices from completely different ones.

Hope this helps!

**Comment by Alexey-Verkhovsky** [comment]
Closing the issue as no feedback provided. Please reopen if it's still persists.
