### ISSUE TITLE
相同设备获取的fingerprint不一致

### ISSUE THREAD

**Issue by lijibing892170** [fingerprintjs/fingerprintjs-android#112]
同一台设备，获取的fingerprint不一致。系统：Android 12，设备：XT2125-4

**Comment by Alexey-Verkhovsky** [comment]
Hello! Can you clarify, please, what are mismatches? What was the mode of fingerprinting? (STABLE, OPTIMAL, UNIQUE)? 
If it's possible to reproduce – you may send us all the data by clicking "report issue" button in demo app.

**Comment by lijibing892170** [comment]
> 你好！请您澄清一下什么是不匹配？指纹采集的方式是什么？（稳定、最佳、独特）？ 如果可以重现 - 您可以通过单击演示应用程序中的“报告问题”按钮向我们发送所有数据。

感谢回复，已解决，谢谢！
