### ISSUE TITLE
Stable device fingerprint is not stable between system updates

### ISSUE THREAD

**Issue by adunayak** [fingerprintjs/fingerprintjs-android#113]
Hi,

I tried the demo app and observed that the device fingerprint with stability level stable changes on system update. I assume we are getting hardware fingerprint for stability level stable. But as per the [table](https://github.com/fingerprintjs/fingerprintjs-android/blob/main/docs/stability.md) hardware fingerprint survives system update but that's not the case. Can you share some insights here to keep it same?

**Comment by Alexey-Verkhovsky** [comment]
Hi! Can you please share more details? What was the device, what was the update (from which version to which)?
Also you may send the dump of the library output through "Report an issue" button in the application.

**Comment by adunayak** [comment]
Thanks for the quick reply. Please find the details below.

Name of the device: Samsung Galaxy A14 5G
Model Name: SM-A146B/DS update - Android security patch 1-Dec-2023

**Comment by adunayak** [comment]
I wanted to share the json file before and after system update. I'e used another samsung device and observed the same issue. Please find the details and json file before and after the system update. I can conclude that hardware fingerprint doesn't remain same on system update.

Device model - Samsung Galaxy A03 core (SM-A033F/DS)
OS upgraded to - Android 12

[before_update.json](https://github.com/fingerprintjs/fingerprintjs-android/files/13935769/before_update.json)
[after_update.json](https://github.com/fingerprintjs/fingerprintjs-android/files/13935770/after_update.json)

**Comment by Alexey-Verkhovsky** [comment]
The difference happened because of changed amount of RAM and total storage space. The fix is simple – to round the value to the more common values (e.g. 8 GB RAM or 128 GB storage) for the stable fingerprint. The fix will be implemented and delivered during Q3 2024.

**Comment by Alexey-Verkhovsky** [comment]
During solving the issue we found that three signals were fluctuating in this particular case.

1. `TotalRamSignal`
2. `TotalInternalStorageSpaceSignal`
3. `SensorsListSignal`

Based on our data, it is not possible to fix those fluctuations without having a significant impact on the uniqueness of the STABLE fingerprint, especially considering that the frequency of these fluctuations is fairly low. 

So we decided not to take any further actions on this issue.

If this doesn't work for you, you may:
1. Use [custom fingerprint API](https://github.com/fingerprintjs/fingerprintjs-android/blob/main/docs/api_reference.md#raw-signals-access-and-custom-fingerprinting) for excluding the signals you don't want to fluctuate by any chance (with the cost of not unique identifier). 
2. Consider using [PRO](https://dev.fingerprint.com/docs/native-android-integration) version.
