### ISSUE TITLE
Android TV support 

### ISSUE THREAD

**Issue by AgnitumuS** [fingerprintjs/fingerprintjs-android#35]
On android tv devices i receive 

com.test.app I/ServiceManager: Waiting for service 'media.camera' on '/dev/binder'...
com.test.app I/ServiceManager: Waiting for service 'media.camera' on '/dev/binder'...
com.test.app I/ServiceManager: Waiting for service 'media.camera' on '/dev/binder'...
com.test.app I/ServiceManager: Waiting for service 'media.camera' on '/dev/binder'...
com.test.app W/ServiceManager: Service media.camera didn't start. Returning NULL
com.test.app W/CameraBase: CameraService not published, waiting...
com.test.app I/ServiceManager: Waiting for service 'media.camera' on '/dev/binder'...
com.test.app I/ServiceManager: Waiting for service 'media.camera' on '/dev/binder'...
com.test.app I/ServiceManager: Waiting for service 'media.camera' on '/dev/binder'...

and app freeze 
how to fix ?

**Comment by Alexey-Verkhovsky** [comment]
Hello! Thanks for the report. I don't have any Android TV devices, so I tried to reproduce the problem via emulators, and everything works fine. Can you provide some details: what is the TV/Emulator you are using? What's the version of  Android?

**Comment by Sergey-Makarov** [comment]
Added workaround in [release 1.3.0](https://github.com/fingerprintjs/fingerprintjs-android/releases/tag/1.3.0)
