### ISSUE TITLE
found anr through GPC

### ISSUE THREAD

**Issue by MKelman** [fingerprintjs/fingerprintjs-android#55]
attached is an image pointing to the fingerprint sdk of an anr from this dependency. any thoughts? this is on version 1.2.

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/10063610/174305662-9e75e01b-50f7-40f3-a618-257c96655d51.png">

**Comment by Alexey-Verkhovsky** [comment]
Hello! Thanks for the report!
Could you provide please a bit more details about the device? Vendor and Android Version, if it's possible.

**Comment by Sergey-Makarov** [comment]
Seems like we can't do much in this case, but at least with the [1.3.0 release](https://github.com/fingerprintjs/fingerprintjs-android/releases/tag/1.3.0) it's not the UI thread that will hang if something like this happens, but a separate one.
Feel free to reopen the issue if you are still facing this problem in any way with the latest version of the library.
