### ISSUE TITLE
Fingerprint changes after device reboot

### ISSUE THREAD

**Issue by aleksandrmozgovoi** [fingerprintjs/fingerprintjs-android#61]
I have almost every reboot change all 3 types of fingerprint (STABLE, OPTIMAL, UNIQUE)
Perhaps your library is bound to the mac address
how to make fingerprint immutable?

**Comment by Alexey-Verkhovsky** [comment]
Hello! Could you please provide some device specs? 

It's very probable connected with [this issue](https://github.com/fingerprintjs/fingerprintjs-android/issues/38). It's fixed, and the new release will be available soon.

**Comment by aleksandrmozgovoi** [comment]
This problem is reproduced on many devices of different models. Here are mine for example
![photo_2022-08-22_13-12-02](https://user-images.githubusercontent.com/17898218/185897141-d2cc3919-e503-4987-ba41-94494494ebc7.jpg)

**Comment by Sergey-Makarov** [comment]
A lot of issues have been solved in [release 1.3.0](https://github.com/fingerprintjs/fingerprintjs-android/releases/tag/1.3.0), so closing this one for now.
Feel free to reopen the issue if it's still reproducible using v1.3.0 of the library with v4 fingerprint.
