### ISSUE TITLE
MediaDrm id not unique for some devices 

### ISSUE THREAD

**Issue by TrolloLogic** [fingerprintjs/fingerprintjs-android#79]
It seems that media drm id is not unique on some device. Almost all of the duplicates are from Vivo devices, some device examples:
```
{
     device_manufacturer: vivo,
     device_model: V2027,
     device_os: 12,
     drmId: b2761ec9e81a8448ad4d7cf48bc55a06aba1789aeaccf2c7374dc101d11fdf5a
},
{
     device_manufacturer: vivo,
     device_model: V2025,
     device_os: 12,
     drmId: b7dd10dc0900f79eee3b77dcd0204a136a2818fef92cca4d09655b8fa64cd5f9
}
```

Are you already familiar with this problem, and do you have some idea how to handle those cases?

**Comment by Alexey-Verkhovsky** [comment]
Hello! 
Yes, it's a known issue. And indeed, most of the FP cases happen on Vivo devices. As a solution you may create a rule, to identify not by media DRM ID but by GSF ID or Android ID for these scenarios, when device manufacturer is Vivo. You'll mostly solve the issue with a way smaller set of exceptions. To cover the rest of the cases you may consider using [PRO](https://github.com/fingerprintjs/fingerprintjs-pro-android-demo).
