### ISSUE TITLE
The displayed name of GSF ID and Android ID in the demo app are swapped.

### ISSUE THREAD

**Issue by yeneihub** [fingerprintjs/fingerprintjs-android#80]
I saw that the demo app is displaying the wrong GSF ID and after I look into the code, I found that the displayed names are swapped. 
<img width="746" alt="Screen Shot 2566-02-01 at 18 02 37" src="https://user-images.githubusercontent.com/44750404/216025401-1d0220a7-b736-44c3-9df1-84a0eba81581.png">

**Comment by Sergey-Makarov** [comment]
Great catch, thanks! This will be fixed with the next update of the app.

**Comment by Alexey-Verkhovsky** [comment]
Fixed [here](https://github.com/fingerprintjs/fingerprintjs-android/pull/84). It will be delivered in the next release. Thanks @tronku for the PR.
