### ISSUE TITLE
Fingerprint Pro result is inconsistent while OSS result is consistent

### ISSUE THREAD

**Issue by omkar-tenkale** [fingerprintjs/fingerprintjs-android#81]
I tried both apps "Fingerprint OSS Demo" and "Fingerprint PRO Demo"
I noted the fingerprint values then factory reset the phone (Samsung Galaxy M21 2021)

Results for Fingerprint OSS Demo
DeviceId different, All v5 fingerprints different except STABLE

Results for Fingerprint PRO Demo
Different IDs returned
Also, after resetting the IP, OS, first seen , last seen  etc displays n/a n/a

**Comment by Alexey-Verkhovsky** [comment]
Hello Omkar! A lot of people all over the world sell or gift their old devices and perform a legit factory reset. The amount of that kind of people way bigger that the amount of fraudulent devices. So the ID changes after factory reset, both – OSS and PRO. 

STABLE fingerprint on OSS only connected to Hardware, so the same model of device with the same will have the same STABLE fingerprint, which may cause a lot of False Positive identifications (and hence – security risks) 

We're will provide a functionality to check if there a recent factory reset took place. And it will be available in the next release of PRO. I'll let you know about it in the issue.
