### ISSUE TITLE
Is that possible to have a Flutter version of fingerprintjs?

### ISSUE THREAD

**Issue by hpp0hpp** [fingerprintjs/fingerprintjs-android#82]
Hi,
Would be a greate help to Flutter developers. 
Thank you

**Comment by Alexey-Verkhovsky** [comment]
Hi! We have a [flutter](https://github.com/fingerprintjs/fingerprintjs-pro-flutter) version of the PRO library. Supporting different frameworks for OSS is in the backlog, but it won't be delivered in the nearest future :( 

If you don't consider using PRO – the source of the bridge code is open, you may use it integrating OSS to your project.
